### ISSUE TITLE
Sub abbreviation expand

### ISSUE THREAD

**Issue by NicholasR** [crittermike/zen-coding-gedit#5]
On habrahabr.ru i found information about new features about zen-coding v0.6.
New zen can expand abbreviations like this one:

div#page>(div#header>ul#nav>li_4>a)+(div#page>(h1>span)+p_2)+div#footer

So, my question: will there ever be carried this function in your plugin?

**Comment by crittermike** [comment]
Yep, I'll be working on this as soon as I get a chance. Thanks for the request.

**Comment by NicholasR** [comment]
thanks for answer

**Comment by crittermike** [comment]
Sorry for the delay, trying to get some free time to knock this out.

**Comment by crittermike** [comment]
This is included now.
