### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by fmarcia** [crittermike/zen-coding-gedit#6]
Do you plan to add placeholders you can navigate with tab, like snippets do, in this amazing plugin?
Besides, do you think it would be possible to merge zen-coding with snippets as well, using tab to expand?
Great work!

**Comment by crittermike** [comment]
1) Yes, it's a 'nice to have' but I have no idea if it's feasible yet or what it will take to accomplish.
2) I was considering removing all non-dynamic abbreviations and instead including snippet presets for them. If that was done, the dynamic stuff (like div>ul>li*6) would still be handled by zencoding, but the preset stuff (like op:ie) would be handled by Snippets, which has a lot more flexibility and customization built in. Thoughts on that?

**Comment by fmarcia** [comment]
Yes, using snippets for static stuff is a good idea. Actually and ideally, zen-coding should be a fork of snippets as it's the same concept: type less, write more! You could use their setting box too!

**Comment by crittermike** [comment]
This is done now that your commits have been merged. Thanks!
