### ISSUE TITLE
Cursor position

### ISSUE THREAD

**Issue by dburles** [crittermike/zen-coding-gedit#7]
When expanding CSS the cursor is positioned outside of the semi-colon rather than just before it

for example you type:

fl(ctrl+e)

it then generates: (the pipe representing the cursor)

float:;|

rather than

float:|;

**Comment by dburles** [comment]
I'm using gedit on windows, another issue is when expanding it's adding multiple newlines and not retaining indentation, example:
        div*5
        div

div

div

div

div

**Comment by crittermike** [comment]
Just commited a fix for the first problem. As for problem #2, can you open a new issue with some more details?

**Comment by dburles** [comment]
thanks for the fix, works great! just going to create a new issue for problem #2..
